sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 10.62.243.141
    port: 3306
    database: sky_take_out
    username: root
    password: 456912378Ndp@
  minio:
    endpoint: http://10.62.243.141:9000
    accessKey: Bl3XwELJJQvyraSDcO4t
    secretKey: nJN7cJQ11JZRlHCXpJltA5T6ZsDv3GtNGXY8Yh4A
    bucketName: ay01


server:
  port: 8082


