sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 10.62.243.141
    port: 3306
    database: sky_take_out
    username: root
    password: 456912378Ndp@
server:
  port: 8082
