sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 10.62.243.141
    port: 3306
    database: sky_take_out
    username: root
    password: 456912378Ndp@
  minio:
    endpoint: http://10.62.243.141:9000
    accessKey: Bl3XwELJJQvyraSDcO4t
    secretKey: nJN7cJQ11JZRlHCXpJltA5T6ZsDv3GtNGXY8Yh4A
    bucketName: ay01
  redis:
    host: 10.62.243.141
    port: 6379
    database: 0
  wechat:
    appid: wx9c38de55f6e9b9fe
    secret: 097a86b8f978778140663cb8646054aa


server:
  port: 8082


